project:
  type: website

website:
  title: "Weltsicht"
  # site-url: https://weltsicht.de
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Tonelock
      - icon: instagram
        href: https://www.instagram.com/ttonelock/
      - legal_notice.qmd
    lang: de
format:
  html:
    theme:
      - sandstone
    css: styles.css




