project:
  type: website

website:
  title: "Alex' Travels"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Tonelock
      - icon: instagram
        href: https://www.instagram.com/ttonelock/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



